@MinimalApiWithSimpleInjector_HostAddress = http://localhost:5266

GET {{MinimalApiWithSimpleInjector_HostAddress}}/product
Accept: application/json

###

GET {{MinimalApiWithSimpleInjector_HostAddress}}/succcessfulproduct
Accept: application/json

###

GET {{MinimalApiWithSimpleInjector_HostAddress}}/withouthttpcontext
Accept: application/json

###

GET {{MinimalApiWithSimpleInjector_HostAddress}}/withcontainerindi
Accept: application/json
